name: Deploy 'Consumer' to Firebase Hosting on merge
'on':
  push:
    branches:
      - master
    # Optionally configure to run only for specific files/folders.
    paths:
      - 'consumer/**'
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Build
        working-directory: './consumer'
        run: npm ci && npm run build

      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ADMIN__SURVEY_APP }}'
          channelId: live
          projectId: admin--survey-app
          # Specific site name from 'firebase.json'
          target: consumer
